export const offlineCities = [
  {
    id: 1,
    name: 'Daska',
    locations: null,
    donor: null,
    createdBy: 1,
    updatedBy: 1,
    createdDateTime: '2017-10-24T12:42:25.9090541',
    updatedDateTime: '2017-10-24T12:42:25.9102273',
    isDeleted: false,
    isActive: true,
  },
  {
    id: 2,
    name: 'Lahore',
    locations: null,
    donor: null,
    createdBy: 1,
    updatedBy: 1,
    createdDateTime: '2017-10-24T12:46:15.4383915',
    updatedDateTime: '2017-10-24T12:46:15.4383934',
    isDeleted: false,
    isActive: true,
  },
  {
    id: 3,
    name: 'Gujranwala',
    locations: null,
    donor: null,
    createdBy: 1,
    updatedBy: 1,
    createdDateTime: '2017-10-24T13:33:56.7393322',
    updatedDateTime: '2017-10-24T13:33:56.7393348',
    isDeleted: false,
    isActive: true,
  },
  {
    id: 4,
    name: 'Sialkot',
    locations: null,
    donor: null,
    createdBy: 1,
    updatedBy: 1,
    createdDateTime: '2017-10-24T13:34:05.8522789',
    updatedDateTime: '2017-10-24T13:34:05.8522807',
    isDeleted: false,
    isActive: true,
  },
  {
    id: 5,
    name: 'Gujrat',
    locations: null,
    donor: null,
    createdBy: 1,
    updatedBy: 1,
    createdDateTime: '2017-10-24T13:34:15.6696938',
    updatedDateTime: '2017-10-24T13:34:15.6696956',
    isDeleted: false,
    isActive: true,
  },
  {
    id: 6,
    name: 'Wazirabad',
    locations: null,
    donor: null,
    createdBy: 1,
    updatedBy: 1,
    createdDateTime: '2022-05-09T11:59:32.4801374',
    updatedDateTime: '2022-05-09T11:59:32.4801388',
    isDeleted: false,
    isActive: true,
  },
];
export const offlineGroups = [
  {
    id: 1,
    value: 'O+',
    description: null,
    patientMaster: null,
    bloodBagTest: null,
    transRequest: null,
    donor: null,
    bloodProducts: null,
    createdBy: 0,
    updatedBy: null,
    createdDateTime: '0001-01-01T00:00:00',
    updatedDateTime: null,
    isDeleted: false,
    isActive: false,
  },
  {
    id: 2,
    value: 'A+',
    description: null,
    patientMaster: null,
    bloodBagTest: null,
    transRequest: null,
    donor: null,
    bloodProducts: null,
    createdBy: 0,
    updatedBy: null,
    createdDateTime: '0001-01-01T00:00:00',
    updatedDateTime: null,
    isDeleted: false,
    isActive: false,
  },
  {
    id: 3,
    value: 'A-',
    description: null,
    patientMaster: null,
    bloodBagTest: null,
    transRequest: null,
    donor: null,
    bloodProducts: null,
    createdBy: 0,
    updatedBy: null,
    createdDateTime: '0001-01-01T00:00:00',
    updatedDateTime: null,
    isDeleted: false,
    isActive: false,
  },
  {
    id: 4,
    value: 'B+',
    description: null,
    patientMaster: null,
    bloodBagTest: null,
    transRequest: null,
    donor: null,
    bloodProducts: null,
    createdBy: 0,
    updatedBy: null,
    createdDateTime: '0001-01-01T00:00:00',
    updatedDateTime: null,
    isDeleted: false,
    isActive: false,
  },
  {
    id: 5,
    value: 'B-',
    description: null,
    patientMaster: null,
    bloodBagTest: null,
    transRequest: null,
    donor: null,
    bloodProducts: null,
    createdBy: 0,
    updatedBy: null,
    createdDateTime: '0001-01-01T00:00:00',
    updatedDateTime: null,
    isDeleted: false,
    isActive: false,
  },
  {
    id: 6,
    value: 'AB+',
    description: null,
    patientMaster: null,
    bloodBagTest: null,
    transRequest: null,
    donor: null,
    bloodProducts: null,
    createdBy: 0,
    updatedBy: null,
    createdDateTime: '0001-01-01T00:00:00',
    updatedDateTime: null,
    isDeleted: false,
    isActive: false,
  },
  {
    id: 7,
    value: 'AB-',
    description: null,
    patientMaster: null,
    bloodBagTest: null,
    transRequest: null,
    donor: null,
    bloodProducts: null,
    createdBy: 0,
    updatedBy: null,
    createdDateTime: '0001-01-01T00:00:00',
    updatedDateTime: null,
    isDeleted: false,
    isActive: false,
  },
  {
    id: 8,
    value: 'O-',
    description: null,
    patientMaster: null,
    bloodBagTest: null,
    transRequest: null,
    donor: null,
    bloodProducts: null,
    createdBy: 0,
    updatedBy: null,
    createdDateTime: '0001-01-01T00:00:00',
    updatedDateTime: null,
    isDeleted: false,
    isActive: false,
  },
];
